desc

diff --git a/update_git b/update_git
--- a/update_git
+++ b/update_git
@@ -7,6 +7,11 @@ git add .
 git commit -m desc
 
 stts=$(git status)
-echo "STATUS:"
-echo $?
 
+if [ "$?" -ne 0 ]
+then
+	echo "Error committing..."
+	exit
+else
+	echo "Ok..."
+if
